---
# Install zsh
install_zsh: true

# Install Linuxbrew
install_linuxbrew: false

# Install asdf-vm
install_asdf: false

# Install Lua programming language
install_lua: false

# Lua version to install
lua_version: "5.3"

# Install Neovim
install_neovim: false

# Install Node.js programming language
install_nodejs: true

# Install Python programming language
install_python: true

# Install Go programming language
install_golang: true

# Install Slack
install_slack: false

# Install Vagrant and VirtualBox
install_vagrant: false

# Install Docker
install_docker: true

# Install Google Cloud SDK
install_gcloud: true

# Install AWS tools
install_aws: true

# Install Terraform
install_terraform: true

# Install Packer
install_packer: false

# Install Ruby and rbenv
install_ruby: false

# Install Rust programming language
install_rust: false

# Install productivity tools
install_productivity: true

# Install antivirus software
install_antivirus: false

# Install security tools
install_security: false

# Update apt cache when running playbooks
update_apt_cache: true

# Do not install Cloud SDK from package manager
gcloud_install_from_package_manager: false

# Install rbenv for the current user
rbenv:
  env: user
  version: v1.1.2
  default_ruby: 2.6.3
  rubies:
    - version: 2.6.3
